// UI/my-app/src/pages/Cart.jsx
import React, { useCallback, useEffect, useState } from "react";
import CartHttpService from "services/http/CartHttpService";
import OrderHttpService from "services/http/OrderHttpService";
import ShopHttpService from "services/http/ShopHttpService";
import CartLine from "components/cart/CartLine";
import { CART_ITEMS_KEY } from "services/CartService";
import "styles/ProductStyle.css";
import { NavLink } from "react-router-dom";
import OrderModal from "components/modal/order/OrderModal";

const cartHttpService = CartHttpService();
const orderHttpService = OrderHttpService();
const shopHttpService = ShopHttpService();

const Cart = () => {
	const [totalPrice, setTotalPrice] = useState(0);
	const [cartItems, setCartItems] = useState([]);
	const [products, setProducts] = useState([]);
	const [shops, setShops] = useState([]);
	const [showModal, setShowModal] = useState(false);
	const [shopId, setShopId] = useState(1);

	// TODO: Think about how do it better
	useEffect(() => {
		let tmp = 0;
		products.forEach(x => {
			setTotalPrice(
				(tmp +=
					(cartItems.find(y => y.productId === x.id)?.quantity ?? 1) * x.price)
			);
		});
	}, [showModal]);

	useEffect(() => {
		setCartItems(() => {
			const items = JSON.parse(window.localStorage.getItem(CART_ITEMS_KEY) ?? "[]");
			Promise.all([
				cartHttpService(items.map(item => item.productId)),
				shopHttpService.getShops(),
			])
				.then(response => {
					setProducts(response[0].data.products);
					setShops(response[1].data.shops);
				})
				.catch(() => {});
			return items;
		});
	}, []);

	const createOrder = useCallback((e) => {
		e.preventDefault();
		orderHttpService
			.postOrder({
				shopId: shopId,
				totalPrice: totalPrice,
				orderLines: cartItems,
			})
			.then(() => {
				setCartItems([]);
				localStorage.removeItem(CART_ITEMS_KEY);
				setShowModal(false);
			});
	});

	const deleteItem = useCallback(item =>
		setCartItems(cartItems => {
			const items = cartItems.filter(elem => elem.productId !== item.productId);
			window.localStorage.setItem(CART_ITEMS_KEY, JSON.stringify(items));
			return items;
		})
	);

	const openModal = useCallback(() => setShowModal(prev => !prev));

	return (
		<>
			<div className="container py-5">
				<h3 className="mb-4">Shopping Bag ({cartItems.length})</h3>
				{cartItems.length > 0 && products.length > 0 && (
					<div className="font-size-sm">
						<div className="row border-bottom border-dark d-none d-md-flex fw-bold">
							<div className="col-4">Name</div>
							<div className="col-5">Note</div>
							<div className="col-1">
								<i className="bi bi-basket"></i>
							</div>
							<div className="col-1">
								<i className="bi bi-wallet"></i>
							</div>
							<div className="col-1">
								<i className="bi bi-x-lg"></i>
							</div>
						</div>
						{cartItems.map(item => (
							<CartLine
								key={item.productId}
								products={products}
								item={item}
								deleteItem={deleteItem}></CartLine>
						))}
						<div className="d-flex justify-content-end mt-2">
							<button
								className="btn btn-outline-dark px-4 py-2"
								onClick={openModal}>
								Order
							</button>
						</div>
					</div>
				)}

				{cartItems.length === 0 && (
					<div className="row">
						<div className="col-12 col-md-4">
							<h5>Your shopping bag is empty.</h5>
							<NavLink to={`/product`}>
								<button className="btn btn-outline-dark mt-2 px-4 py-2">
									Continue Browsing
								</button>
							</NavLink>
						</div>
					</div>
				)}
			</div>
			<OrderModal
				shops={shops}
				setShopId={setShopId}
				totalPrice={totalPrice}
				createOrder={createOrder}
				isActive={showModal}
				setActive={openModal}
			/>
		</>
	);
};

export default Cart;

// UI/angular/src/app/features/cart/pages/cart/cart.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { forkJoin } from 'rxjs';
import { finalize } from 'rxjs/operators';

import { CartItem } from 'src/app/models/cart/cartItem';
import { Loadable } from 'src/app/models/loadable';
import { Order } from 'src/app/models/order/order';
import { Product } from 'src/app/models/product/product';
import { Shop } from 'src/app/models/shop/shop';
import { OrderDashboardComponent } from 'src/app/module/order-dashboard/order-dashboard.component';
import { AuthService } from 'src/app/services/auth.service';
import { CartHttpService } from 'src/app/services/http/cart.http.service';
import { OrderHttpService } from 'src/app/services/http/order.http.service';
import { ShopHttpService } from 'src/app/services/http/shop.http.service';

export const CART_ITEMS = ('CartItemArray');

@Component({
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.css']
})
export class CartComponent extends Loadable implements OnInit {

  private _productIds: number[] = <number[]>[]

  totalPrice: number = 0;
  cartItems: CartItem[] = <CartItem[]>[]
  items: Product[] = <Product[]>[];
  shops: Shop[] = <Shop[]>[];

  constructor(
    private _modalService: NgbModal,
    private _cartHttpService: CartHttpService,
    private _orderHttpService: OrderHttpService,
    private _authService: AuthService,
    private _shopHttpService: ShopHttpService,
    private _router: Router
  ) {
    super();
  }

  ngOnInit() {
    this.loadPageInfo();
  }

  getProductByProductId(productId: number): Product {
    return this.items.find(x => x.id === productId) ?? <Product>{};
  }

  loadPageInfo() {
    this.enableLoading();
    this.cartItems = JSON.parse(localStorage.getItem(CART_ITEMS) || '[]');
    this._productIds = this.cartItems.map(x => x.productId);
    forkJoin({
      cartItem: this._cartHttpService
        .getCartItem(this._productIds),
      shopList: this._shopHttpService
        .getShops()
    }).pipe(finalize(() => this.disableLoading()))
      .subscribe(({ cartItem, shopList }) => {
        this.items = cartItem.products;
        this.shops = shopList.shops;
      });
  }

  delete(index: number) {
    if (index >= 0) {
      this.cartItems = JSON.parse(localStorage.getItem(CART_ITEMS) || '[]');
      this.cartItems.splice(index, 1);
      localStorage.setItem(CART_ITEMS, JSON.stringify(this.cartItems));
      this.loadPageInfo();
    }
  }

  onOrderClick() {
    if (this._authService.isAuthenticated())
      this.addOrder();
    else {
      this._authService.login();
      this._authService
        .isAutorise
        .subscribe(() => this.addOrder());
    }
  }

  addOrder() {
    this.totalPrice = 0;
    this.items.forEach(x => {
      this.totalPrice += (this.cartItems.find(y => y.productId === x.id)?.quantity ?? 1) * x.price;
    });
    const modalRef = this._modalService.open(OrderDashboardComponent, { centered: true });
    const module = <OrderDashboardComponent>modalRef.componentInstance;
    module.totalPrice = this.totalPrice;
    module.shops = this.shops;
    module.order.subscribe((item: Order) => {
      item.totalPrice = this.totalPrice;
      item.orderLines = this.cartItems;
      module.activeModal.close();
      this._orderHttpService.postOrder(item).subscribe(() => {
        localStorage.removeItem(CART_ITEMS);
        this.cartItems = [];
        this.items = [];
        this._router.navigate(['account/order']);
      });
    });
  }
}

<div class="container py-5">
  <h3 class="mb-4">Shopping Bag ({{cartItems.length}})</h3>
  <app-loadable [active]="isLoading">
    <div class="font-size-sm"
         *ngIf="cartItems.length > 0">
      <div class="row border-bottom border-dark d-none d-md-flex fw-bold">
        <div class="col-4">Name</div>
        <div class="col-5">Note</div>
        <div class="col-1"><i class="bi bi-basket"></i></div>
        <div class="col-1"><i class="bi bi-wallet"></i></div>
        <div class="col-1"><i class="bi bi-x-lg"></i></div>
      </div>
      <div class="row border-bottom border-dark py-2"
           *ngFor="let dataItem of cartItems;let i = index">
        <div class="col-12 col-md-4">
          <span class="d-md-none fw-bold">Name: </span>
          <span>{{getProductByProductId(dataItem.productId).name}}</span>
        </div>
        <div class="col-12 col-md-5">
          <span class="d-md-none fw-bold">Note: </span>
          <span>{{dataItem.note}}</span>
        </div>
        <div class="col-12 col-md-1">
          <span class="d-md-none fw-bold">Quantity: </span>
          <span>{{dataItem.quantity}}</span>
        </div>
        <div class="col-12 col-md-1 d-flex justify-content-between mb-2">
          <span>
            <span class="d-md-none fw-bold">Price: </span>
            <span>${{dataItem.quantity * getProductByProductId(dataItem.productId).price}}</span>
          </span>
          <button class="btn btn-outline-dark d-md-none"
                  (click)="delete(i)">Delete
          </button>
        </div>
        <div class="col-12 col-md-1">
          <button class="btn d-none d-md-block"
                  (click)="delete(i)">
            <i class="bi bi-trash"></i>
          </button>
        </div>
      </div>
      <div class="d-flex justify-content-end mt-2">
        <button class="btn btn-outline-dark px-4 py-2"
                (click)="onOrderClick()">
          Order
        </button>
      </div>
    </div>

    <div class="row"
         *ngIf="cartItems.length === 0">
      <div class="col-12 col-md-4">
        <h5>Your shopping bag is empty.</h5>
        <button routerLink="/"
                class="btn btn-outline-dark mt-2 px-4 py-2">
          Continue Browsing
        </button>
      </div>
    </div>
  </app-loadable>
</div>
